name:                     "Crowdsourcing"
sub-name:                 "Crowdsourcing for the Humanities"
markdown:                 redcarpet
highlighter:              pygments
description:              "A research project at the Center for Spatial and Textual Analysis (CESTA), Stanford University."
category_dir :
category_title_prefix :   ''
category_title :          ''
google_id:                ''
disqus:                   ''
url:                      http://0.0.0.0:4000
permalink:                /:year/:month/:day/:title/

links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Tools
    url: /tools/
  - title: People
    url: /people/

projects:
  - title: Living with the Railroads
    url: living-with-railroads
  - title: Year of the Bay
    url: year-of-the-bay
  - title: Emotions of London
    url: emotions-of-london
